[build]
  command = "ng build --configuration production && ng run nomis-terminal:serverless:production"
  publish = "dist/nomis-terminal/browser"

[[plugins]]
  package = "@netlify/plugin-angular-universal"
